// backend code
// ie --> server code

console.log("My server is running");

var express = require('express');

// app --> application
// using the constructor to create an express app
var app = express();

// create our server
var server = app.listen(3000);

// || ---> OR operator
// var port = process.env.PORT || 3000;
// var server = app.listen(port);

// have my application use files in the public folder
app.use(express.static('public'));

var socket = require('socket.io');

// create a variable that keeps track of inputs and outputs
var io = socket(server);

// set up a connection event - ie new car of the highway lane
// second parameter - callback
io.sockets.on('connection', newConnection);

// node packages for our twitter account
const Twit = require("twit");
const request = require("request");
const fs = require("fs");

var config = require('./config.js');
var T = new Twit(config);

var tweet = "Here is an image generated from my fun drawing app!";
  

function newConnection(socket){
    console.log("new connection! " + socket.id);

    socket.on('circle', circleMsg);
    socket.on('emoji', emojiMsg);
    socket.on('clear', clearMsg);
    socket.on('tweet', tweetMsg);

    function circleMsg(data){
        // console.log(data);
        socket.broadcast.emit('circle', data);
    }

    function emojiMsg(data){
        // console.log(data);
        socket.broadcast.emit('emoji', data);
    }

    function clearMsg(){
        // broadcast sends to every browser (ie client)
        // expect the browser that sent the message
        socket.broadcast.emit('clear');
    }

    function tweetMsg(data){
        var filename = "public/images/myCanvas" + data.imgNum + ".png"
        // encode the image!
		var encoded_img = fs.readFileSync(filename, {encoding: 'base64'});
		T.post('media/upload', {media_data: encoded_img}, insertMetaData);

        function insertMetaData(error, data, response){
            if(error){
                console.log(error);
            }
            var mediaIdStr = data.media_id_string;
            var altText = "This is an image generated by a p5 drawing sketch";
            var meta_params = { media_id: mediaIdStr, alt_text: { text: altText } };
    
            T.post('media/metadata/create', meta_params, createdMedia);
    
            function createdMedia(error, data, response){
                if(error){
                    console.log(error);
                }
                var tweet_parameters = {status: tweet, media_ids: mediaIdStr};
                T.post('statuses/update', tweet_parameters, tweeted);
            }
        }
    
        // this function let's us know if everything is OK - 
        // you could also look at your Twitter profile
        function tweeted(error, data, response){
            if(error){
            console.log(error);
            } else {
            console.log("You're doing great! " + data.text);
            }
        }
    }
}
